version: "3.4"

services:

    minitube:
      build: .
      container_name: minitube-go
      restart: always
      ports:
        - "80:80"
      depends_on:
        - live
        - redis
        - mysql
      command: ["wait-for-it", $MYSQL_ADDR, "-t", "2", "-q", "--", "./minitube"]
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ADDR=${MYSQL_ADDR}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_ADDR=${REDIS_ADDR}
        - LIVE_ADDR=${LIVE_ADDR}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}
        - DEBUG=${DEBUG}
      

    live:
      image: icceey/livego
      container_name: minitube-live
      restart: always
      ports:
        - "1935:1935"
        - "8080:7001"
      depends_on:
        - redis
      environment:
        - REDIS_ADDR=${REDIS_ADDR}
        - REDIS_PASSWORD=${REDIS_PASSWORD}


    redis:
      image: redis:alpine
      container_name: minitube-redis
      restart: always
      expose:
        - "6379"
      volumes:
        - ./config/redis.conf:/usr/local/etc/redis/redis.conf
        - ./redis-healthcheck.sh:/usr/local/bin/healthcheck
      command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
      environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
      healthcheck:
        test: ["CMD", "healthcheck"]
        start_period: 8s
        interval: 4s
        timeout: 1s
        retries: 3
    
        
    mysql:
      image: mysql
      container_name: minitube-mysql
      restart: always
      expose:
        - "3306"
      volumes:
        - ./config/my.cnf:/etc/mysql/my.cnf
        - ./mysql-healthcheck.sh:/usr/local/bin/healthcheck
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      healthcheck:
        test: ["CMD", "healthcheck"]
        start_period: 32s
        interval: 8s
        timeout: 2s
        retries: 3


