version: "3"

services:

    minitube:
      build: .
      container_name: minitube-go
      restart: always
      ports:
        - "80:80"
      depends_on:
        - live
        - redis
        - mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ADDR=${MYSQL_ADDR}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_ADDR=${REDIS_ADDR}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}

    live:
        image: icceey/livego
        container_name: minitube-live
        restart: always
        ports:
            - "1935:1935"
            - "8080:7001"
            - "8090"
        depends_on:
            - redis
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}

    redis:
        image: redis:alpine
        container_name: minitube-redis
        restart: always
        expose:
          - "6379"
        volumes:
          - ./config/redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    
    mysql:
      image: mysql
      container_name: minitube-mysql
      restart: always
      expose:
        - "3306"
      volumes:
        - ./config/my.cnf:/etc/mysql/my.cnf
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
